### PR TITLE
Added Gemfile and initialize load-path when including the gem

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by adamcooke** [comment]
Is there a good reason for changing the `require_relative` to change the load path?

**Comment by skateman** [comment]
Hm, it is the default if you generate a dummy gem using `bundle gem`. I can change it back if you would like to keep it ...

**Comment by adamcooke** [comment]
`require_relative` is shorter and more concise so would be better to keep it. The `.gitignore` is also a bit large for this project (I assume another auto generated file).

I would have expected to see a `Gemfile.lock` too with the addition of the `Gemfile`. Is there any reason for adding the `Gemfile`?

**Comment by skateman** [comment]
Yup, I copied an auto-generated `.gitignore`. I prefer specifying versions in the `gemspec` and not pushing the `Gemfile.lock` as it can surprise some people on other platforms than mine.

I would like to have some integration with my development pipeline and with `bundler`. I'm planning to implement some additional features provided by the plug.

**Comment by adamcooke** [comment]
Best practice says that the lockfile should be checked into the repository (and is what I do in all my projects). Perfectly happy to have a Gemfile though, it's often useful. I've added it quickly into `master`. Right now, I don't see any need for the large gitignore or the change to the gemspec. 

New features, though, I'd love them 👍

**Pull request closed without merging**
